trigger:
  - develop
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js 16.x"
# install angular & dependencies

# build for production

# run eslint

# run unit tests

# test coverage

# run sonar?

# archive files

# build docker image

# push to dockerhub
