trigger:
  - develop
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js 16.x"

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: "Install angular & dependencies"

  - script: |
      ng build --configuration production
    displayName: "Build for production"
# Run eslint

# Run unit tests

# Test coverage

# Run sonar?

# Archive files

# Build docker image

# Push to dockerhub
