trigger:
  - develop
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js 16.x"

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: "Install angular & dependencies"

  - script: |
      ng lint
    displayName: "Run linting with ESLint" # control when does not lint

  - script: |
      ng test --watch=false --browsers=ChromeHeadless --reporters=junit --code-coverage
    displayName: "Run testing" # control when does not pass

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "**/TESTS-*.xml"
      testRunTitle: "Publish test results"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/**/*.xml"

  # Run sonar?

  - script: |
      ng build --configuration production
    displayName: "Build for production"
# Archive files

# Build docker image

# Push to dockerhub
