trigger:
  - develop
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js 16.x"

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: "Install angular & dependencies"

  - script: |
      ng lint
    displayName: "Run linting with ESLint"

  # Run unit tests

  # Test coverage

  # Run sonar?

  - script: |
      ng build --configuration production
    displayName: "Build for production"
# Archive files

# Build docker image

# Push to dockerhub
